# Generated by Django 4.2.1 on 2023-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
